name: Test app

on:
  workflow_dispatch:
  push:
    branches-ignore:
    - "main"
    - "master"

  
  
jobs:
  test:
    name: Testing iOS app
    runs-on: macos-15
    # https://github.com/actions/runner-images/blob/main/README.md#available-images
    env:
      project-name: FefeReader
      scheme-name: FefeReader
      platform: iOS\ Simulator,OS=18.1
      phone: iPhone\ 16\ Pro
      # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md#installed-simulators

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Select XCode 16.1
        run: sudo xcode-select -switch /Applications/Xcode_16.1.app
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md#xcode

      - name: Testing iOS app
        run: |
          set -eo pipefail

          xcodebuild -project ${{ env.project-name }}.xcodeproj \
                      -scheme ${{ env.scheme-name }} \
                      -destination platform=${{ env.platform }},name=${{ env.phone }} \
                      clean test | xcpretty
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md#installed-simulators
