name: Test app

on:
  - push
  - pull_request
  
jobs:
  test:
    name: Testing iOS app
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Force XCode 15.0
        run: sudo xcode-select -switch /Applications/Xcode_15.0.app
      - name: Testing iOS app
        run: exec ./.github/scripts/test_app.sh
